#!/bin/bash
# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) 2019 Daniel Borkmann <daniel@iogearbox.net>

usage()
{
  cat <<-EOF
  usage: pw-pull [-h] [-t TREE] [-s SINCE_COMMIT]
EOF
  exit
}

remote=""
since=""
tree=""
today=$(date +%Y-%m-%d)
while true; do
  case "$1" in
    -s | --since ) since="$2"; shift 2 ;;
    -t | --tree ) tree="$2"; shift 2 ;;
    -h | --help ) usage; break ;;
    * )  break ;;
  esac
done
[ -z "$since" ] && usage
[ -z "$tree" ]  && usage
case $tree in
  bpf-next ) remote=(net-next git://git.kernel.org/pub/scm/linux/kernel/git/bpf/$tree.git) ;;
  bpf ) remote=(net git://git.kernel.org/pub/scm/linux/kernel/git/bpf/$tree.git) ;;
  * ) usage ;;
esac
file="pr-$tree-$today.patch"
git request-pull $since ${remote[1]} > $file
echo -e "Subject: pull-request: $tree $today\n\nHi David,\n\nThe following pull-request contains BPF updates for your *${remote[0]}* tree.\n\nThe main changes are:\n\n1) ..., from XYZ. Among others:\n\n    - Blah blah sub item.\n\n2) ..., from ABC.\n\nPlease consider pulling these changes from:\n\n  git://git.kernel.org/pub/scm/linux/kernel/git/bpf/$tree.git\n\nThanks a lot!\n\n----------------------------------------------------------------\n\n$(cat $file)" > $file
bug=$(grep -c gitolite $file)
if [ "$bug" -gt "0" ]; then
  echo "PR not generated: using gitolite url, not public one!"
  rm -f $file
else
  echo "PR: $file"
fi
